//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""DesktopFarm"",
            ""id"": ""2dfccc14-83fc-423f-b82b-022c1ee96ccc"",
            ""actions"": [
                {
                    ""name"": ""GrowPlants"",
                    ""type"": ""Button"",
                    ""id"": ""e1cdf7cd-fccf-4c76-83a9-1d1d7b8b9184"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""eb643f02-67f7-44f5-af29-ae8fbf061187"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrowPlants"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // DesktopFarm
        m_DesktopFarm = asset.FindActionMap("DesktopFarm", throwIfNotFound: true);
        m_DesktopFarm_GrowPlants = m_DesktopFarm.FindAction("GrowPlants", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // DesktopFarm
    private readonly InputActionMap m_DesktopFarm;
    private List<IDesktopFarmActions> m_DesktopFarmActionsCallbackInterfaces = new List<IDesktopFarmActions>();
    private readonly InputAction m_DesktopFarm_GrowPlants;
    public struct DesktopFarmActions
    {
        private @PlayerControls m_Wrapper;
        public DesktopFarmActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @GrowPlants => m_Wrapper.m_DesktopFarm_GrowPlants;
        public InputActionMap Get() { return m_Wrapper.m_DesktopFarm; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DesktopFarmActions set) { return set.Get(); }
        public void AddCallbacks(IDesktopFarmActions instance)
        {
            if (instance == null || m_Wrapper.m_DesktopFarmActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DesktopFarmActionsCallbackInterfaces.Add(instance);
            @GrowPlants.started += instance.OnGrowPlants;
            @GrowPlants.performed += instance.OnGrowPlants;
            @GrowPlants.canceled += instance.OnGrowPlants;
        }

        private void UnregisterCallbacks(IDesktopFarmActions instance)
        {
            @GrowPlants.started -= instance.OnGrowPlants;
            @GrowPlants.performed -= instance.OnGrowPlants;
            @GrowPlants.canceled -= instance.OnGrowPlants;
        }

        public void RemoveCallbacks(IDesktopFarmActions instance)
        {
            if (m_Wrapper.m_DesktopFarmActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDesktopFarmActions instance)
        {
            foreach (var item in m_Wrapper.m_DesktopFarmActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DesktopFarmActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DesktopFarmActions @DesktopFarm => new DesktopFarmActions(this);
    public interface IDesktopFarmActions
    {
        void OnGrowPlants(InputAction.CallbackContext context);
    }
}
